### ISSUE TITLE
ToDo Items

### ISSUE THREAD

**Issue by sophiemiddleton** [Mu2e/REve#104]
CRV:
 - [x] CRV Coincidence Clusters
 - [x]  CRV-aligned bars
 - [x] CRV 3D display bar highlights
 - [x] Fix nominal positioning
 - [x] CRV display improvements (2D)
 - [x] Add access to Crv reco pulses via clusters

 
Calo:
 - [x]  CaloClusters lego plot and fix
 - [x] Highlight "crystals hit"
 - [ ] Proportional colors
 - [ ] Cluster axis
 - [x]  Crystals for extracted view
 - [x] Remove CRV from the general YZ view (simple as adding a flag in draw)
 - [x] Add CaloDigi with access to crystals via SiPMID
 
General:
 - [x]  Add Error bar option as fcl parameter/draw opt
 - [x]  Need to redesign TrkHit plotting to not require ComboHits
 - [x] Fix seg fault in CaloClusters
 - [ ] Add TrkCaloHit to KalSeed options
 - [ ] Make 2D displays more optional
 - [x] Make sure TrkHit visually has all features of combo hit display
 - [ ]  Print time information or have some sort of scale for that
 - [ ] improve labelling of data products
 - [x] improve geometry handling - remove hardcoded numbers

Buttons:
- [x] working quit
- [ ] working save

**Comment by sophiemiddleton** [comment]
coincidence clusters added and tested
